# Generated by Django 5.0.1 on 2024-01-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="contactFormModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=50, verbose_name="Adınız soyadınız"),
                ),
                ("message", models.TextField(max_length=200, verbose_name="Mesajınız")),
            ],
        ),
    ]
